# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chaotic ramblings
email: abdelrhmanshawky4@gmail.com
description: ShawkyZ Ramblings
baseurl: "" # the subpath of your site, e.g. /blog
highlighter: rouge
lang: "en"
url: "https://ramblings.shawkyz.info" # the base hostname & protocol for your site
enforce_ssl: shawkyz.info
twitter_username: "shawkyz1"
facebook_username: "shawkyz1"
linkedin_username: "shawkyz"
github_username:  "shawkyz"
disqus_username:  "shawkyz"

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

sass:
  sass_dir: assets/_sass
  style: compressed

images: '/assets/images'
